#ifndef _PG_INDEPENDENT_PAGES_H_
#define _PG_INDEPENDENT_PAGES_H_

typedef enum _PG_PREOP_CALLBACK_STATUS {
    PG_PREOP_CALL_POST_AND_FIND_SIZE,
    PG_PREOP_NOT_CALL_POST,
    PG_PREOP_BREAK
} PG_PREOP_CALLBACK_STATUS;

typedef PG_PREOP_CALLBACK_STATUS(NTAPI *PG_CALLBACK_PREOP)(PVOID Va, SIZE_T size, PVOID CallbackContext, PVOID* PostContext);

typedef BOOLEAN(NTAPI *PG_CALLBACK_POSTOP)(PVOID Va, SIZE_T size, PVOID CallbackContext, PVOID PostContext, PHASHTABLE pHashTable);

typedef POOL_TYPE(NTAPI *FNMiDeterminePoolType)(PVOID Va);

typedef struct _PG_OPERATION_CALLBACKS
{
    PG_CALLBACK_PREOP PreCallBack;
    PG_CALLBACK_POSTOP PostCallBack;
}PG_OPERATION_CALLBACKS, *PPG_OPERATION_CALLBACKS;

typedef BOOLEAN(NTAPI *ENUMPHYSICALCALLBACK)(PVOID Va, SIZE_T size, PVOID context);

NTSTATUS PgIdpEnumPhysicalMemoryEx(PPG_OPERATION_CALLBACKS callbacks, PVOID context);

NTSTATUS PgIdpInitialization();

BOOLEAN PgIdpMmIsExecutebleAddress(PVOID Address);

BOOLEAN PgIdpMmIsAccessibleAddress(PVOID Address);

#endif
